name: build_test_search_and_book

on:
  push:
    branches:
      - main
      - dev
      - test
jobs:
  build_test_notify:
    name: build_and_release_android
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.6'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk
      - name: Push to github Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{github.run_number}}
          allowUpdates: true
          generateReleaseNotes: false
          makeLatest: true
      - name: Download firebase cli
        run: |
          curl -sL https://firebase.tools | bash
          echo "$HOME/.firebase/bin" >> $GITHUB_PATH
      - name: Login to firebase
        run: firebase login:ci --no-localhost
        env: 
            FIREBASE_TOKEN: 
              ${{ secrets.FIREBASE_TOKEN }}
      - name: Upload artifacts to firebase app distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          releaseNotes: "Release Notes"
          releaseNotesFile: "release-notes.txt"
          groups: android_testers
          file: "build/app/outputs/flutter-apk/app-release.apk"


